name: Gitlab Mirror

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Git configuration
        run: |
          git config --global user.name "${{ secrets.GITLAB_USER_NAME }}"
          git config --global user.email "${{ secrets.GITLAB_USER_EMAIL }}"
      - name: Add GitLab remote
        run: git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/endeavouros-filemirror/Branding.git
      - name: Push to GitLab
        run: git push --mirror gitlab
